- hosts: localhost
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  tasks: 
    - include: tasks/ssh.yml
    - include: tasks/git-setup.yml
    - include: tasks/brew.yml
    - include: tasks/nvim.yml
