#!/usr/bin/env bash

## Install ansible
sudo apt-add-repository "deb http://ppa.launchpad.net/ansible/ansible/ubuntu bionic main"
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
sudo apt-get update 
sudo apt-get install ansible -y 

## pull ansible
sudo ansible-pull --vault-pass-file=pass --ask-become-pass --ask-become-pass -U https://github.com/joostderuijter/ansible
