#!/usr/bin/env bash

## Install ansible
sudo apt-add-repository -y ppa:ansible/ansible
sudo apt-get update -y
sudo apt-get install -y curl git software-properties-common ansible

sudo ansible-pull --vault-pass-file=pass --ask-become-pass --ask-become-pass -U https://github.com/joostderuijter/ansible
