- name: Install cmake
  become: true
  apt:
    name: ["cmake"]
  tags:
    - neovim
    - core
- name: Install Clang
  become: true
  apt:
    name: ["clang"]
  tags:
    - neovim
    - core
- name: Install system packages for Neovim
  become: true
  apt:
    name: ["ninja-build","gettext","libtool","libtool-bin","autoconf","automake","cmake","g++","pkg-config","unzip","curl","doxygen"]
  tags:
    - neovim
    - core
