- name: Install stow
  become: true
  apt: name=stow
  tags:
    - dotfiles
    - stow
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:joostderuijter/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - dotfiles
    - stow
- name: Remove default .zshrc
  shell: rm ~/.zshrc
  tags:
    - dotfiles
    - stow
- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./install
  tags:
    - dotfiles
    - stow
