- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "hi@joost.im"
  tags:
    - git-personal
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "Joost"
  tags:
    - git-personal
